#cloud-config
package_update: true
package_upgrade: false

packages:
  - curl
  - git

write_files:
  - path: /usr/local/bin/install_vue.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      VUE_VERSION=$APP_VERSION

      echo "Installing Vue $APP_VERSION..."

      npm install -g create-vue

      create-vue my-app --default

      cd my-app
      npm install vue@$APP_VERSION

      echo "Vue $APP_VERSION installed" > /var/log/vue-version.txt
      npm list vue >> /var/log/vue-version.txt

runcmd:
  - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  - apt-get install -y nodejs
  - /usr/local/bin/install_vue.sh
