#cloud-config
packages:
  - apache2
  - php
  - php-mysql
  - php-intl
  - php-zip
  - php-curl
  - php-bcmath
  - php-soap
  - php-gd
  - php-xml
  - curl
  - unzip
  - git
  - mariadb-server

write_files:
  - path: /usr/local/bin/install_magento.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e
      MAGENTO_VERSION=$APP_VERSION

      echo "Installing Magento $APP_VERSION..."
      cd /var/www
      composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition=$APP_VERSION magento

      chown -R www-data:www-data /var/www/magento
      chmod -R 755 /var/www/magento

runcmd:
  - curl -sS https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer
  - /usr/local/bin/install_magento.sh
