#cloud-config
packages:
  - apache2
  - php
  - php-mysql
  - unzip
  - curl
  - mariadb-server

write_files:
  - path: /usr/local/bin/install_drupal.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e
      DRUPAL_VERSION=$APP_VERSION

      echo "Installing Drupal $APP_VERSION..."
      cd /tmp
      curl -LO https://ftp.drupal.org/files/projects/drupal-$APP_VERSION.tar.gz
      tar -xzf drupal-$APP_VERSION.tar.gz
      mv drupal-$APP_VERSION /var/www/drupal

      chown -R www-data:www-data /var/www/drupal
      chmod -R 755 /var/www/drupal

runcmd:
  - /usr/local/bin/install_drupal.sh
