#cloud-config
package_update: true
package_upgrade: false

packages:
  - apache2
  - php
  - php-mysql
  - php-intl
  - php-zip
  - php-curl
  - php-bcmath
  - php-soap
  - php-gd
  - php-xml
  - php-mbstring
  - curl
  - unzip
  - mariadb-server

write_files:
  - path: /usr/local/bin/install_concrete.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e
      CONCRETE_VERSION="$APP_VERSION"

      echo "Installing Concrete CMS $CONCRETE_VERSION..."
      cd /tmp
      curl -LO https://github.com/concretecms/concretecms/releases/download/$CONCRETE_VERSION/concrete-cms-$CONCRETE_VERSION.zip
      unzip -q concrete-cms-$CONCRETE_VERSION.zip -d /tmp/concrete-temp

      mkdir -p /var/www/concrete
      mv /tmp/concrete-temp/concrete-cms-$CONCRETE_VERSION/* /var/www/concrete/
      rm -rf /tmp/concrete-temp

      chown -R www-data:www-data /var/www/concrete
      chmod -R 755 /var/www/concrete

  - path: /usr/local/bin/setup_mysql_concrete_user.sh
    permissions: "0700"
    content: |
      #!/bin/bash
      set -e

      DB_NAME="concrete_db"
      DB_USER="concrete_user"

      DB_PASS=$(openssl rand -base64 12 | tr -d -c '[:alnum:]')
      PASS_FILE="/.mysql_pass"

      echo "$DB_PASS" > "$PASS_FILE"

      echo "Creating MySQL database and user..."
      mysql -u root -e "CREATE DATABASE IF NOT EXISTS $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
      mysql -u root -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
      mysql -u root -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';"
      mysql -u root -e "FLUSH PRIVILEGES;"

  - path: /usr/local/bin/install_concrete_cli.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      SITE_NAME="My Concrete Site"
      ADMIN_USER="admin"

      ADMIN_PASS=$(openssl rand -base64 12 | tr -d -c '[:alnum:]')
      ADMIN_EMAIL="admin@example.com"
      DB_NAME="concrete_db"
      DB_USER="concrete_user"
      DB_PASS=$(cat /.mysql_pass)


      ADMIN_PASS_FILE="/.admin_pass"
      echo "$ADMIN_PASS" > "$ADMIN_PASS_FILE"


      echo "Running Concrete CMS CLI installation..."

      cd /var/www/concrete

      rm -f application/config/database.php
      rm -f application/config/app.php

      sudo -u www-data ./concrete/bin/concrete5 c5:install \
        --site="$SITE_NAME" \
        --db-server=localhost \
        --db-username="$DB_USER" \
        --db-password="$DB_PASS" \
        --db-database="$DB_NAME" \
        --admin-email="$ADMIN_EMAIL" \
        --admin-password="$ADMIN_PASS" \
        --language="en_US"

      echo "Concrete CMS installed successfully!"
      chown -R www-data:www-data /var/www/concrete

  - path: /etc/apache2/sites-available/concrete.conf
    permissions: "0644"
    content: |
      <VirtualHost *:80>
          ServerAdmin webmaster@localhost
          DocumentRoot /var/www/concrete

          <Directory /var/www/concrete>
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>

          ErrorLog ${APACHE_LOG_DIR}/concrete_error.log
          CustomLog ${APACHE_LOG_DIR}/concrete_access.log combined
      </VirtualHost>

runcmd:
  - /usr/local/bin/install_concrete.sh
  - /usr/local/bin/setup_mysql_concrete_user.sh
  - /usr/local/bin/install_concrete_cli.sh
  - a2dissite 000-default.conf
  - a2ensite concrete.conf
  - a2enmod rewrite
  - systemctl reload apache2

