#cloud-config
package_update: true
package_upgrade: false

packages:
  - nginx
  - mariadb-server
  - curl
  - sqlite3

write_files:
  - path: /usr/local/bin/install_ghost.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      GHOST_VERSION=$APP_VERSION

      echo "Installing Ghost CLI..."
      npm install -g ghost-cli@latest

      mkdir -p /var/www/ghost
      chown -R debian:debian /var/www/ghost

      su - debian -c "
        cd /var/www/ghost && \
        ghost install local --no-start
      "

runcmd:
  - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  - apt-get install -y nodejs
  - /usr/local/bin/install_ghost.sh
  - su - debian -c " cd /var/www/ghost && npm install sqlite3 --save"
  - su - debian -c " cd /var/www/ghost && ghost start"
