#cloud-config

package_update: true
package_upgrade: false

packages:
  - apache2
  - unzip
  - curl
  - mariadb-server
  - openssl
  - ca-certificates
  - lsb-release
  - apt-transport-https
  - gnupg

write_files:
  - path: /usr/local/bin/install_php_for_joomla.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      JOOMLA_VERSION="6-0-1"
      MAJOR_VERSION="$(echo "$JOOMLA_VERSION" | cut -d'-' -f1)"

      # Sury repo (для PHP 8.3/8.4 на Debian 12)
      apt-get update
      apt-get install -y ca-certificates apt-transport-https lsb-release gnupg
      install -d /etc/apt/keyrings
      curl -fsSL https://packages.sury.org/php/apt.gpg -o /etc/apt/keyrings/sury-php.gpg
      echo "deb [signed-by=/etc/apt/keyrings/sury-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/sury-php.list
      apt-get update

      if [ "$MAJOR_VERSION" -ge 6 ]; then
        PHPV="8.4"
      else
        PHPV="8.3"
      fi

      apt-get install -y \
        "php${PHPV}" \
        "libapache2-mod-php${PHPV}" \
        "php${PHPV}-mysql" \
        "php${PHPV}-mbstring" \
        "php${PHPV}-xml" \
        "php${PHPV}-zip" \
        "php${PHPV}-gd" \
        "php${PHPV}-curl" \
        "php${PHPV}-intl"

      a2dismod php8.2 >/dev/null 2>&1 || true
      a2enmod "php${PHPV}" rewrite
      update-alternatives --set php "/usr/bin/php${PHPV}" || true

      systemctl restart apache2

  - path: /usr/local/bin/install_joomla.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      JOOMLA_VERSION="6-0-1"
      MAJOR_VERSION="$(echo "$JOOMLA_VERSION" | cut -d'-' -f1)"

      echo "Installing Joomla $JOOMLA_VERSION..."
      cd /tmp
      curl -fL "https://downloads.joomla.org/cms/joomla${MAJOR_VERSION}/${JOOMLA_VERSION}/Joomla_${JOOMLA_VERSION}-Stable-Full_Package.zip" -o joomla.zip
      unzip -o joomla.zip -d /var/www/joomla

      chown -R www-data:www-data /var/www/joomla
      chmod -R 755 /var/www/joomla

  - path: /usr/local/bin/setup_mysql_joomla_user.sh
    permissions: "0700"
    content: |
      #!/bin/bash
      set -e

      DB_NAME="joomla_db"
      DB_USER="joomla_user"

      DB_PASS=$(openssl rand -base64 12 | tr -d -c '[:alnum:]')
      PASS_FILE="/.mysql_pass"

      echo "$DB_PASS" > "$PASS_FILE"

      mysql -u root -e "CREATE DATABASE IF NOT EXISTS $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
      mysql -u root -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
      mysql -u root -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';"
      mysql -u root -e "FLUSH PRIVILEGES;"

  - path: /usr/local/bin/install_joomla_cli.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      SITE_NAME="My Joomla Site"
      ADMIN_USER="admin"

      ADMIN_PASS=$(openssl rand -base64 12 | tr -d -c '[:alnum:]')
      ADMIN_EMAIL="admin@example.com"

      DB_TYPE="mysqli"
      DB_HOST="localhost"
      DB_USER="joomla_user"
      DB_PASS_FILE="/.mysql_pass"
      DB_PASS=$(cat "$DB_PASS_FILE")
      DB_NAME="joomla_db"

      ADMIN_PASS_FILE="/.admin_pass"
      echo "$ADMIN_PASS" > "$ADMIN_PASS_FILE"

      chown -R www-data:www-data /var/www/joomla

      sudo -u www-data php /var/www/joomla/installation/joomla.php install \
        --site-name="$SITE_NAME" \
        --admin-user="$ADMIN_USER" \
        --admin-username="admin" \
        --admin-password="$ADMIN_PASS" \
        --admin-email="$ADMIN_EMAIL" \
        --db-type="$DB_TYPE" \
        --db-host="$DB_HOST" \
        --db-user="$DB_USER" \
        --db-pass="$DB_PASS" \
        --db-name="$DB_NAME" \
        -n

  - path: /etc/apache2/sites-available/joomla.conf
    permissions: "0644"
    content: |
      <VirtualHost *:80>
          ServerAdmin webmaster@localhost
          DocumentRoot /var/www/joomla

          <Directory /var/www/joomla>
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>

          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
      </VirtualHost>

runcmd:
  - /usr/local/bin/install_php_for_joomla.sh
  - /usr/local/bin/install_joomla.sh
  - /usr/local/bin/setup_mysql_joomla_user.sh
  - /usr/local/bin/install_joomla_cli.sh
  - a2dissite 000-default.conf
  - a2ensite joomla.conf
  - systemctl reload apache2
