#cloud-config

package_update: true
package_upgrade: false

packages:
  - apache2
  - php
  - php-mysql
  - curl
  - unzip
  - mariadb-server

write_files:
  - path: /usr/local/bin/install_wp_cli.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e
      echo "Installing WP-CLI..."
      curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      chmod +x wp-cli.phar
      mv wp-cli.phar /usr/local/bin/wp

  - path: /usr/local/bin/install_wordpress.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e
      WP_VERSION=${APP_VERSION}

      echo "Installing WordPress $WP_VERSION..."
      mkdir -p /var/www/
      cd /tmp
      curl -LO https://wordpress.org/wordpress-$WP_VERSION.tar.gz
      tar -xzf wordpress-$WP_VERSION.tar.gz
      mv wordpress /var/www/wordpress

      chown -R www-data:www-data /var/www/wordpress
      chmod -R 755 /var/www/wordpress

  - path: /usr/local/bin/setup_mysql_user.sh
    permissions: "0700"
    content: |
      #!/bin/bash
      set -e

      DB_USER="wpuser"
      DB_PASS=$(openssl rand -base64 12 | tr -d -c '[:alnum:]')
      PASS_FILE="/.mysql_pass"

      echo "$DB_PASS" > "$PASS_FILE"

      echo "Creating MySQL database and user..."
      mysql -u root -e "CREATE DATABASE IF NOT EXISTS wordpress;"
      mysql -u root -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
      mysql -u root -e "GRANT ALL PRIVILEGES ON wordpress.* TO '$DB_USER'@'localhost';"
      mysql -u root -e "FLUSH PRIVILEGES;"

  - path: /usr/local/bin/setup_wordpress_admin.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      WP_PATH="/var/www/wordpress"
      WP_TITLE="My WordPress Site"
      WP_ADMIN_USER="admin"
      WP_ADMIN_PASS=$(openssl rand -base64 12 | tr -d -c '[:alnum:]')
      WP_ADMIN_EMAIL="admin@example.com"
      DB_PASS=$(cat /.mysql_pass)

      ADMIN_PASS_FILE="/.admin_pass"
      echo "$WP_ADMIN_PASS" >> "$ADMIN_PASS_FILE"

      echo "Configuring WordPress using WP-CLI..."

      wp config create \
        --path=$WP_PATH \
        --dbname=wordpress \
        --dbuser=wpuser \
        --dbpass="$DB_PASS" \
        --dbhost=localhost \
        --skip-check \
        --force \
        --allow-root

      wp core install \
        --path=$WP_PATH \
        --url="$URL" \
        --title="$WP_TITLE" \
        --admin_user="$WP_ADMIN_USER" \
        --admin_password="$WP_ADMIN_PASS" \
        --admin_email="$WP_ADMIN_EMAIL" \
        --allow-root

      chown -R www-data:www-data $WP_PATH

  - path: /etc/apache2/sites-available/wordpress.conf
    permissions: "0644"
    content: |
      <VirtualHost *:80>
          ServerAdmin webmaster@localhost
          Servername $URL
          DocumentRoot /var/www/wordpress

          <Directory /var/www/wordpress>
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>

          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
      </VirtualHost>

runcmd:
  - /usr/local/bin/install_wp_cli.sh
  - /usr/local/bin/install_wordpress.sh
  - /usr/local/bin/setup_mysql_user.sh
  - /usr/local/bin/setup_wordpress_admin.sh
  - a2dissite 000-default.conf
  - a2ensite wordpress.conf
  - a2enmod rewrite
  - systemctl reload apache2
