#cloud-config
package_update: true
package_upgrade: false
packages:
  - gnupg
  - curl
  - ca-certificates

runcmd:
  - |
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc |
      gpg --dearmor -o /usr/share/keyrings/postgresql-archive-keyring.gpg
  - |
    echo "deb [signed-by=/usr/share/keyrings/postgresql-archive-keyring.gpg] \
      https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" \
      > /etc/apt/sources.list.d/pgdg.list
  - apt-get update
  - |
    apt-get install -y \
      postgresql-$APP_VERSION \
      postgresql-contrib-$APP_VERSION
  - systemctl enable --now postgresql
