#cloud-config
package_update: true
package_upgrade: false

packages:
  - curl
  - ca-certificates
  - gnupg
  - lsb-release
  - debconf-utils

runcmd:
  - curl -fsSL https://couchdb.apache.org/repo/keys.asc | gpg --dearmor -o /usr/share/keyrings/couchdb-archive-keyring.gpg
  - |
    source /etc/os-release
    echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main" > /etc/apt/sources.list.d/couchdb.list
  - apt-get update

  - echo "couchdb couchdb/mode select standalone" | debconf-set-selections
  - echo "couchdb couchdb/bindaddress string 0.0.0.0" | debconf-set-selections
  - echo "couchdb couchdb/adminpass password admin" | debconf-set-selections
  - echo "couchdb couchdb/adminpass_again password admin" | debconf-set-selections

  - COUCH_FULL_VERSION=$(apt-cache madison couchdb | grep "$DB_VERSION" | head -n1 | awk '{print $3}') && \
    echo "Installing CouchDB $COUCH_FULL_VERSION" && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y couchdb=$COUCH_FULL_VERSION

  - systemctl enable --now couchdb


