#cloud-config
package_update: true
package_upgrade: false

packages:
  - curl
  - ca-certificates
  - gnupg
  - lsb-release

write_files:
  - path: /usr/local/bin/install_couchdb.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      DB_VERSION="$DB_VERSION"

      # Импорт ключа CouchDB
      curl -fsSL https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null

      # Добавление APT-источника
      source /etc/os-release
      echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main" \
        > /etc/apt/sources.list.d/couchdb.list

      apt-get update

      COUCH_FULL_VERSION=$(apt-cache madison couchdb | grep "$DB_VERSION" | head -n1 | awk '{print $3}')

      if [ -z "$COUCH_FULL_VERSION" ]; then
        echo "CouchDB version $DB_VERSION not found"
        exit 1
      fi

      echo "Installing CouchDB version: $COUCH_FULL_VERSION"
      DEBIAN_FRONTEND=noninteractive apt-get install -y couchdb=$COUCH_FULL_VERSION

      systemctl enable --now couchdb

runcmd:
  - /usr/local/bin/install_couchdb.sh
