#cloud-config
package_update: true
package_upgrade: false

packages:
  - gnupg
  - curl
  - ca-certificates

runcmd:
  - |
    curl -fsSL https://pgp.mongodb.com/server-$APP_VERSION.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-server-$APP_VERSION.gpg
  - |
    echo "deb [signed-by=/usr/share/keyrings/mongodb-server-$APP_VERSION.gpg] \
      https://repo.mongodb.org/apt/debian bookworm/mongodb-org/$APP_VERSION main" \
      > /etc/apt/sources.list.d/mongodb-org-$APP_VERSION.list
  - apt-get update
  - |
    DEBIAN_FRONTEND=noninteractive apt-get install -y mongodb-org
  - systemctl enable --now mongod