#cloud-config
package_update: true
package_upgrade: false

packages:
  - nodejs
  - npm
  - curl
  - git

write_files:
  - path: /usr/local/bin/install_vue.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      VUE_VERSION=$APP_VERSION

      echo "Installing Vue  $APP_VERSION..."
      npm create vue@$APP_VERSION my-app -- --default
    
      echo "Vue $APP_VERSION installed" > /var/log/vue-version.txt
      vue --version >> /var/log/vue-version.txt

runcmd:
  - /usr/local/bin/install_vue.sh
