#cloud-config
package_update: true
package_upgrade: false

packages:
  - curl
  - apt-transport-https
  - dotnet-sdk-7.0

write_files:
  - path: /usr/local/bin/install_dotnet.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      DOTNET_VERSION=$DOTNET_VERSION

      echo "Installing .NET SDK $DOTNET_VERSION..."

      wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      chmod +x dotnet-install.sh
      ./dotnet-install.sh --version $DOTNET_VERSION --install-dir /opt/dotnet

      ln -s /opt/dotnet/dotnet /usr/local/bin/dotnet

      echo ".NET $DOTNET_VERSION installed" > /var/log/dotnet-version.txt
      dotnet --version >> /var/log/dotnet-version.txt

runcmd:
  - /usr/local/bin/install_dotnet.sh
