#cloud-config
package_update: true
package_upgrade: false

packages:
  - curl
  - php
  - php-cli
  - php-mbstring
  - php-xml
  - php-bcmath
  - php-curl
  - php-mysql
  - unzip
  - git
  - zip
  - php-zip
  - php-tokenizer
  - php-json
  - php-common
  - php-mysqlnd
  - php-sqlite3
  - sqlite3

write_files:
  - path: /usr/local/bin/install_laravel.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      LARAVEL_VERSION=$APP_VERSION

      echo "Installing Composer..."
      curl -sS https://getcomposer.org/installer | php
      mv composer.phar /usr/local/bin/composer

      echo "Creating Laravel project (version $APP_VERSION)..."
      mkdir -p /var/www/laravel
      cd /var/www/laravel

      composer create-project laravel/laravel="^$APP_VERSION" .

      echo "Laravel $APP_VERSION successfully installed" > /var/log/laravel-version.txt
      php artisan --version >> /var/log/laravel-version.txt

      chown -R www-data:www-data /var/www/laravel
      chmod -R 755 /var/www/laravel

runcmd:
  - /usr/local/bin/install_laravel.sh
