#cloud-config
package_update: true
package_upgrade: false

packages:
  - nodejs
  - npm
  - curl
  - git

write_files:
  - path: /usr/local/bin/install_angular.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      ANGULAR_VERSION=$ANGULAR_VERSION

      echo "Installing Angular CLI $ANGULAR_VERSION..."
      npm install -g @angular/cli@$ANGULAR_VERSION

      echo "Angular CLI $ANGULAR_VERSION installed" > /var/log/angular-version.txt
      ng version >> /var/log/angular-version.txt

runcmd:
  - /usr/local/bin/install_angular.sh
