#cloud-config
package_update: true
package_upgrade: false

packages:
  - curl
  - git
  - nodejs
  - npm

write_files:
  - path: /usr/local/bin/install_express.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      EXPRESS_VERSION=$APP_VERSION

      echo "Installing Express.js $APP_VERSION..."

      mkdir -p /opt/express-app
      cd /opt/express-app

      npm init -y
      npm install express@$APP_VERSION

      echo "Express $APP_VERSION installed" > /var/log/express-version.txt
      node -p "require('express/package.json').version" >> /var/log/express-version.txt

runcmd:
  - /usr/local/bin/install_express.sh
