#cloud-config
package_update: true
package_upgrade: false

packages:
  - git
  - curl
  - build-essential
  - libssl-dev
  - libreadline-dev
  - zlib1g-dev
  - libsqlite3-dev
  - sqlite3
  - libffi-dev
  - libyaml-dev
  - autoconf
  - bison

write_files:
  - path: /usr/local/bin/install_rails.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      RAILS_VERSION=$APP_VERSION
      RUBY_VERSION=3.2.2

      echo "Installing Ruby via rbenv and Rails $APP_VERSION..."

      git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      cd ~/.rbenv && src/configure && make -C src
      echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
      echo 'eval "$(rbenv init - bash)"' >> ~/.bashrc
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init - bash)"

      git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

      rbenv install -s $RUBY_VERSION
      rbenv global $RUBY_VERSION

      gem install bundler
      gem install rails -v "$APP_VERSION"

      echo "Rails $APP_VERSION installed with Ruby $RUBY_VERSION" > /var/log/rails-version.txt
      rails --version >> /var/log/rails-version.txt

runcmd:
  - /usr/local/bin/install_rails.sh
