#cloud-config
package_update: true
package_upgrade: false

packages:
  - python3
  - python3-pip
  - python3-venv
  - curl
  - ca-certificates
  - build-essential

write_files:
  - path: /usr/local/bin/install_flask.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      FLASK_VERSION=$APP_VERSION

      echo "Installing Flask version: $APP_VERSION..."

      python3 -m venv /opt/flask-env
      source /opt/flask-env/bin/activate

      pip install --upgrade pip setuptools
      pip install flask==$APP_VERSION

      echo "Flask $APP_VERSION installed in /opt/flask-env"
      flask --version > /var/log/flask-version.txt

runcmd:
  - /usr/local/bin/install_flask.sh
