#cloud-config
package_update: true
package_upgrade: false

packages:
  - python3
  - python3-pip
  - python3-venv
  - curl
  - ca-certificates
  - build-essential

write_files:
  - path: /usr/local/bin/install_django.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      DJANGO_VERSION=$APP_VERSION

      echo "Installing Django version: $APP_VERSION..."

      python3 -m venv /opt/django-env
      source /opt/django-env/bin/activate

      pip install --upgrade pip setuptools
      pip install django==$APP_VERSION

      django-admin --version > /var/log/django-version.txt
      echo "Django $APP_VERSION installed in /opt/django-env"

runcmd:
  - /usr/local/bin/install_django.sh
